MOVEMENT_BASE_PHYSICAL = "physical"
MOVEMENT_BASE_SPECIAL = "special"
MOVEMENT_BASE_STATUS = "status"
MOVEMENT_BASE = (
    (MOVEMENT_BASE_PHYSICAL, MOVEMENT_BASE_PHYSICAL),
    (MOVEMENT_BASE_SPECIAL, MOVEMENT_BASE_SPECIAL),
    (MOVEMENT_BASE_STATUS, MOVEMENT_BASE_STATUS),
)
